/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dell' at '6/15/18 12:26 AM' with Gradle 2.14.1
 *
 * @author Dell, @date 6/15/18 12:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
